url: http://www.bullriverbody.com
baseurl: 

# Site settings
title: Bull River Body Shop
email: bullriverbodyshop@yahoo.com
description: "The premier body shop on route 56."


# Team names, titles and social links
people:
- name: Steve Labelle
  pic: 1
  position: Owner and Lead Technician ASTE
  social:
    - title: facebook
      url: #
  

- name: Shannon Wilder
  pic: 2
  position: Office Manager 
  social:
    - title: facebook
      url: #

- name: Hailey Labelle 
  pic: 3
  position: Daughter
  social:
    - title: facebook
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/Bull-River-Body-Shop-151726354869854/?fref=ts
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
